default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development: &development
  <<: *default
  database: realestate
  hostname: localhost
  username: hs
  password: root

test:
  <<: *development

production:
  <<: *default

